global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Pour récupérer les métriques de votre API Node.js tournant sur Windows
  - job_name: 'node-backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:3000']
